"""
3x4 comparison table reading the existing results for each config.

Reads the evaluation JSON files generated by evaluation/evaluate.py and builds
a comparison table between the MAE/MSE/SSIM models.

Usage:
    python comparison/loss_table.py --code_dim 128
    python comparison/loss_table.py --mae mae:128 --mse mse:128 --ssim ssim:128
    python comparison/loss_table.py --configs mae:128 mse:256 ssim:128
"""

import argparse
import csv
import json
import sys
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from rich.console import Console
from rich.table import Table
from rich import box

from core import configuration as cfg

console = Console()

KEYS       = ["mae",            "mse",            "ssim"]
ROW_LABELS = ["MODELO MAE (L1)", "MODELO MSE (L2)", "MODELO SSIM"]


def _metrics_dir(rec_mode: str, code_dim: int) -> Path:
    return cfg.exp_metrics_dir(rec_mode, code_dim, "reconstruction", "per_class")


def read_metrics(rec_mode: str, code_dim: int, ckpt_label: str) -> dict:
    json_path = _metrics_dir(rec_mode, code_dim) / f"eval_test_{ckpt_label}.json"
    if not json_path.exists():
        raise FileNotFoundError(f"No se encontró: {json_path}\n"
                                f"  Ejecuta primero: python evaluation/evaluate.py "
                                f"--rec_mode {rec_mode} --code_dim {code_dim}")
    with open(json_path) as f:
        d = json.load(f)
    return {
        "epoch":     d.get("epoch", "?"),
        "n_samples": d.get("n_samples", "?"),
        "l1":        d["mae_gaussiana"]["mean"],
        "l2":        d["mse_gaussiana"]["mean"],
        "ssim":      d["ssim_gaussiano"]["mean"],
        "psnr":      d["psnr_db"]["mean"],
    }


COLS = [
    ("Modelo (pérdida entren.)", "cyan",   "left"),
    ("n_test",                   "white",  "right"),
    ("L1 (MAE)",                 "yellow", "right"),
    ("L2 (MSE)",                 "yellow", "right"),
    ("SSIM",                     "green",  "right"),
    ("PSNR (dB)",                "blue",   "right"),
]


def print_table(rows: list, label: str):
    t = Table(title=f"[bold]{label}[/bold]  —  máscara gaussiana (Opción B)",
              box=box.DOUBLE_EDGE, show_lines=True)
    for name, style, justify in COLS:
        t.add_column(name, style=style, justify=justify)
    for r in rows:
        t.add_row(
            r["row_label"], str(r["n_samples"]),
            f"{r['l1']:.6f}", f"{r['l2']:.6f}",
            f"{r['ssim']:.6f}", f"{r['psnr']:.3f}",
        )
    console.print(t)


def save_csv(rows: list, csv_path: Path, label: str):
    fieldnames = ["row_label", "run_name", "epoch", "n_samples",
                  "l1", "l2", "ssim", "psnr"]
    with open(csv_path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)
        f.write(f"\n# Tabla: {label}\n")
        f.write(f"# Métricas: máscara gaussiana (Opción B), evaluadas sobre test set propio de cada run\n")
    print(f"  CSV guardado en: {csv_path}")


def save_markdown(rows_best: list, rows_last: list, md_path: Path):
    def md_table(rows):
        lines = [
            "| Modelo (pérdida entren.) | n_test | L1 (MAE) | L2 (MSE) | SSIM | PSNR (dB) |",
            "|:-------------------------|-------:|---------:|---------:|-----:|----------:|",
        ]
        for r in rows:
            lines.append(
                f"| {r['row_label']} | {r['n_samples']} "
                f"| {r['l1']:.6f} | {r['l2']:.6f} "
                f"| {r['ssim']:.6f} | {r['psnr']:.3f} |"
            )
        return "\n".join(lines)

    with open(md_path, "w") as f:
        f.write("# Loss Table — comparativa L1 / L2 / SSIM\n\n")
        f.write("> Métricas con máscara gaussiana centrada (Opción B).  \n")
        f.write(f"> Generado: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
        f.write("## BEST.PT\n\n")
        f.write(md_table(rows_best))
        f.write("\n\n## LAST.PT\n\n")
        f.write(md_table(rows_last))
        f.write("\n")
    print(f"  Markdown guardado en: {md_path}")


def parse_args():
    p = argparse.ArgumentParser(
        description="Tabla comparativa entre modelos MAE/MSE/SSIM a partir de results existentes."
    )
    g = p.add_mutually_exclusive_group(required=True)
    g.add_argument("--code_dim", type=int, default=None,
                   help="Dimensión compartida para los tres modelos (mae/mse/ssim).")
    g.add_argument("--configs",  nargs=3, metavar="REC_MODE:CODE_DIM",
                   help="Tres configs explícitas: mae:128 mse:128 ssim:128")
    return p.parse_args()


def _parse_configs(args) -> list:
    """Return [(rec_mode, code_dim), ...] for [mae, mse, ssim]."""
    if args.code_dim:
        return [("mae", args.code_dim), ("mse", args.code_dim), ("ssim", args.code_dim)]
    result = []
    for spec in args.configs:
        parts = spec.split(":")
        if len(parts) != 2:
            raise ValueError(f"Formato inválido '{spec}'. Usa rec_mode:code_dim (p.ej. mae:128)")
        result.append((parts[0], int(parts[1])))
    return result


def main():
    args      = parse_args()
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    configs   = _parse_configs(args)

    for (rec_mode, code_dim), label in zip(configs, ROW_LABELS):
        print(f"  {label:<22}: {rec_mode}/dim_{code_dim}")

    rows_best = []
    rows_last = []

    for (rec_mode, code_dim), label in zip(configs, ROW_LABELS):
        config_tag = f"{rec_mode}/dim_{code_dim}"
        mb = read_metrics(rec_mode, code_dim, "best")
        ml = read_metrics(rec_mode, code_dim, "last")
        rows_best.append({"row_label": label, "run_name": config_tag, **mb})
        rows_last.append({"row_label": label, "run_name": config_tag, **ml})
        print(f"\n  {label}  (epoch best={mb['epoch']}, last={ml['epoch']})")
        print(f"    best → L1={mb['l1']:.6f}  L2={mb['l2']:.6f}  SSIM={mb['ssim']:.6f}  PSNR={mb['psnr']:.3f}")
        print(f"    last → L1={ml['l1']:.6f}  L2={ml['l2']:.6f}  SSIM={ml['ssim']:.6f}  PSNR={ml['psnr']:.3f}")

    print_table(rows_best, "BEST.PT")
    print_table(rows_last, "LAST.PT")

    out_dir = cfg.exp_comparativa_dir("2_metrics")
    print()
    save_csv(rows_best, out_dir / f"loss_table_{timestamp}_best.csv", "BEST.PT")
    save_csv(rows_last, out_dir / f"loss_table_{timestamp}_last.csv", "LAST.PT")
    save_markdown(rows_best, rows_last, out_dir / f"loss_table_{timestamp}.md")
    print(f"\nFicheros en: {out_dir}")


if __name__ == "__main__":
    main()
